version: '3.8'

services:
  dev:
    build:
      context: .
    env_file:
      - .env.development
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - APP_NAME=${APP_NAME}
    ports:
      - "8081:8080"

  production:
    build:
      context: .
    env_file:
      - .env.production
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - APP_NAME=${APP_NAME}
    ports:
      - "8080:8080"