version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - APP_NAME=${APP_NAME}
    ports:
      - "8080:8080"
